### ISSUE TITLE
Button is not visible

### ISSUE THREAD

**Issue by RGKleid** [natalieperna/layout-trello#16]
Just installed this extension in chrome and cannot see the button.  Chrome shows the extension is installed and enabled. Logged out and back in and still not visible.

**Comment by RGKleid** [comment]
Solved the problem.  The issue was adblock.  Thanks for writing this extension.

**Comment by mwhittet** [comment]
@RGKleid feel free to close this off :-)

**Comment by natalieperna** [comment]
@RGKleid @mwhittet Thank you!
