### ISSUE TITLE
So how is this supposed to work?

### ISSUE THREAD

**Issue by FamilyTreks** [natalieperna/layout-trello#19]
Installed the chrome extension List Layout on Trello's recommendation.  Nothing happens. I can't find any instructions. Installed other Trello extensions and they worked fine right off the bat.

The description makes it sound like it's just a toggle button, click it to change your grid from horizontal to vertical.

**Comment by natalieperna** [comment]
The toggle button is in the top-right of the page. I need to update the screenshots to make it more obvious where to find it.

I'm closing this issue assuming that was the only problem. If not, leave a comment and I will re-open.

![image](https://cloud.githubusercontent.com/assets/1953083/16120371/437b7440-33ad-11e6-887c-845d1d43536d.png)
