### ISSUE TITLE
Greyed out icon

### ISSUE THREAD

**Issue by kjp99** [natalieperna/layout-trello#20]
Hi - seems like a great tool, but for some reason when I install it the extension is greyed out in my Chrome toolbar and no icon appears in my Trello. But there is a check next to 'enabled' in my list of extensions.

I tired a few other Trello extensions to see if the same thing happened. Generally everything works fine with the most popular ones but with the more obscure ones I get this same problem.

Any idea what the issue might be?

**Comment by natalieperna** [comment]
Open a Trello board page, force refresh with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> (or <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>), then click the button in the top-right corner, as in the screenshot below:
![437b7440-33ad-11e6-887c-845d1d43536d](https://cloud.githubusercontent.com/assets/1953083/16197645/d9f555d2-36d0-11e6-8b32-99256fe77b03.png)

If that button still doesn't appear, then try opening a Trello board in a Chrome incognito window, with all extensions disabled except for this one. If it works there, then it's likely a conflict with another extension, which you can isolate by enabling one other extension at a time.

**Comment by kjp99** [comment]
Thanks for your response.It's very odd: I tried force refreshing, to no avail. I also disabled every other extension, and reinstalled yours, but it still appears as grey in my toolbar. If I click on the icon, I get a drop-down with: 'list layouts for trello', which takes me to the Chrome extension page; 'Options', which is grayed out; 'remove from chrome'; 'hide in chrome menu'; 'manage extensions' (which shows it enabled); and 'inspect popup', which is grayed out.

Do you know if there's a chrome setting or something else that messes with your extension? Thanks again!

**Comment by natalieperna** [comment]
The icon in the toolbar doesn't do anything, it's the button that is added to the top-right of the page (see red outline in the screenshot above) that toggles the layouts.

This might have been a poor design choice, I really just made the extension for myself and my personal preference is avoiding things cluttering up my toolbar if they're only applicable to one website, so I added a button to the board page instead. When I have some free time to dedicate to this I might rethink it.

I'm closing this issue as solved, but if it still isn't working just post another message here and I'll re-open it.

**Comment by kjp99** [comment]
Sorry, I didn't explain myself properly - I do understand that; the icon with the red outline in the screenshot above doesn't appear for me at all. Nothing appears to the right of the bell for me.

**Comment by natalieperna** [comment]
No idea why that's happening, but this is not the first issue with just getting the embedded button to appear. I think this is probably the wrong way to do the extension. Using the toolbar button just makes more sense, and would be more reliable and easier to maintain.

If I can fix this issue and #15, then it'd be worth it, so I'll try to get to it this week or weekend.

**Comment by kjp99** [comment]
That would be really great - thanks a lot! I can't seem to isolate the problem: I've tried it on three different PCs with the same result. Given that it works for others, this is very strange!

**Comment by natalieperna** [comment]
@kjp99 I'm hoping this issue is resolved with the most recent updates. Would you be willing to test the development version of the extension before I release it? Instructions for installing from source are available here: [INSTALL.md](https://github.com/natalieperna/layout-trello/blob/master/INSTALL.md).

**Comment by kjp99** [comment]
I tested it - now works perfectly. (ie. I don't get an icon in my trello interface; instead, when I click on the browser extension when I'm in a board, it toggles between layouts ).

I really appreciate your work!
