### ISSUE TITLE
Bring back button inside of the trello.

### ISSUE THREAD

**Issue by grpace** [natalieperna/layout-trello#22]
Now in full screen mode you cannot change the viewing mode! Please give us the option to have the old functionality back. Thanks!

**Comment by grpace** [comment]
Keyboard shortcut would be totally fine! Thanks for the response Natalie.

**Comment by natalieperna** [comment]
I've added a keyboard shortcut that cycles through the layout options. It's in Version 3.1 which should be available from the Chrome webstore any minute. I went with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd>, but you can customize this by going to `chrome://extensions/` and clicking "Keyboard shortcuts" at the bottom of the page.
