### ISSUE TITLE
No longer working on Vivaldi

### ISSUE THREAD

**Issue by oldengray** [natalieperna/layout-trello#25]
I have been using this extension for many months on Vivaldi, but the next to last release of the browser seems to have broken it, and I can no longer activate it in Trello.  Would love to have it back.

**Comment by natalieperna** [comment]
I'm not familiar with Vivaldi. Do you have anything like Developer Tools in Chrome? Can you check the Javascript console to see if any errors are being thrown when you try to load the extension?

**Comment by oldengray** [comment]
Natalie,

Thank you for your quick response!

I am not an expert on browsers at all, but my understanding is that Vivaldi
is built on Chromium, and it does have Developer Tools.

I cleared the Console and loaded List Layouts. Nothing displayed. Then I
opened a Trello board and the items shown on the pdf screenshot attached
displayed. I have no idea if that helps you or not.

Mike (real name)


On Wed, Sep 21, 2016 at 9:38 AM Natalie Perna [Masked]
<FWD-737QTYSMENAIYCQANIQDAMKAOYAHQASQCDQGGPACRZAIYELQAHTQBFQBEFGGCFTKESZFAMYEWEWCSY3BADWHHPRTVRXKGQ5BA6DCY5DQQZTEK4WBJZRUSIQEVQCQEWDBMCAHCLRONUFKAAGIEREABFABAYALMACOAA3ABTRUWZMCG3BCNQQTRMIMAE4CQQBAAAQA====@
opayq.com> wrote:

**Comment by natalieperna** [comment]
I think when you respond to this thread via email, the attachments get lost. Can you re-attach the photo to a message composed on the issue webpage?: https://github.com/natalieperna/layout-trello/issues/25

**Comment by oldengray** [comment]
Will do.

On Thu, Sep 22, 2016 at 9:59 AM Natalie Perna [Masked]
<FWD-737QTYSMENAIYCQANIQDAMKAOYAHQASQCDQGGTAQGMJCQBIAM6QHMMBJGAM2CAEGAC4ADUI3XUHCAOHLMR3DFM3DYIDS6BBZEJMDEZAM2FU6OSDYIC5E5ORM3QHPEGBRDMLARZBGJRGT2ABBFBUCQIDUEFTCCFRAFYQBMIJORBLNAA7YAL4ADEIRKBARAVEIEZAAAIAAEA======@
opayq.com> wrote:

**Comment by oldengray** [comment]
Here it is.
[Trello.pdf](https://github.com/natalieperna/layout-trello/files/488070/Trello.pdf)

**Comment by oldengray** [comment]
Any ideas?

**Comment by natalieperna** [comment]
Sorry, nothing useful in the log. I'm not looking to expand support to other browsers, since Chrome/Chromium are all I use. I'll leave the issue open though and might look into it in the future when I have more time.

**Comment by oldengray** [comment]
OK, thanks

On Mon, Sep 26, 2016 at 10:30 AM Natalie Perna [Masked]
<FWD-737QTYSMENAIYCQANIQDAMKAOYAHQASQCDQGGTAO4AE3M7BDDQABHJIC4QDIMFWRBQQHHRYOTRUTOA45PDBEWUS4QV4GARASENAAJZKMOVHIWARECSUAUEZJ4JEOAQBNIZVQINYZGBONS5BAAVRCCYADYADVABGQAGIABUAFSMTNKQB6MA3GAK2EVVISK4NRKHKEAIAAEA======@
opayq.com> wrote:

**Comment by spellitwithaph** [comment]
Hi @oldengray, I'm not seeing any issues with the plugin using Vivaldi (1.4.589.38) on MacOS (10.11.6). Could have been that specific release and not related to the plugin itself.

![giphy](https://cloud.githubusercontent.com/assets/173196/19478520/e72f74be-9510-11e6-9a9c-7b9fdbd3a774.gif)

**Comment by oldengray** [comment]
Stephen,

I am now on Vivaldi 1.5.638.3 on Win 10 and the problem persists, so it
wasn't a single Vivaldi release that broke the extension, but every release
over the last couple of months.

List Layouts still works on Chrome, but I prefer Vivaldi.

Too bad, as it makes Trello less user friendly for me.

Mike (aka oldengray)



On Tue, Oct 18, 2016 at 5:58 AM Stephen [Masked]
<FWD-737QTYSMENAIYCQANIQDAMKAOYAHQASQCDQGGTAQGMAIMJHTIBJQSJABKIJOKFSACNQDWJR4W47GATRADQSWFCCLGMBY4NDZDVETEE2BXMIKCBK6DYYBJGASKAICGMUXKOQUTZAJWMNCEABCKCYFAILIENGCELBALQQCYIS46EWYAB6QAXIAGARE6EBAAUKYNC5CAIAAEA======@
opayq.com> wrote:

**Comment by spellitwithaph** [comment]
@oldengray, it looks like that version is a snapshot build and a release on the stable channel. I guess I would expect that snapshot builds will have some issues.

That said, I was able to get the plugin working with the snapshot build you're using on Win10 though I had the extension installed in the stable version then updated to the snapshot version you're using. Not sure if that made any difference though.

![giphy](https://cloud.githubusercontent.com/assets/173196/19484780/c0a750a8-9526-11e6-8bba-5376fa99fcbb.gif)

**Comment by oldengray** [comment]
Stephen,

Based on your comments, I installed the stable build as a stand alone
version of Vivaldi, copied my Default profile from the snapshot version
into stable, and List Layouts works.

I went back to the snapshot version and List Layouts also works (!).

I have no idea what was going on, but at least the extension is working
again.

Thanks very much for your suggestion.

Mike


On Tue, Oct 18, 2016 at 8:35 AM Stephen [Masked]
<FWD-737QTYSMENAIYCQANIQDAMKAOYAHQASQCDQGGTAG4ZNCGWFRA2ZCIJRQYIHDYAFZFAWGEUQUGVS2EAFZPB4DDJAKSAKPCYPAAUBHF2DGKYWGEASWDI2FZMREQ43TKQ3DDRUCCYRUVQACKIKBEARVAJYYERMCCOBALASTTQC24AHYAC4AAXSEXJAOUUHEMRPCAAQAAIA=@
opayq.com> wrote:

**Comment by natalieperna** [comment]
Glad it's solved, thank you @spellitwithaph! I'll consider this a weird one-off edge case then, maybe specifically related to non-stable releases of the browser, but it probably doesn't need further investigating, so closing the issue now.

**Comment by ericblade** [comment]
For anyone else that lands here -- load up trello.com and open a board, and see if there's a bright blue Trello icon in your *address bar*.  Apparently Vivaldi puts site specific extensions (that are properly made site specific) into the address bar, and global extensions on the right side where Chrome does.

**Comment by natalieperna** [comment]
Thanks, @ericblade. It's a shame that Chrome doesn't do this anymore. Even though it's my own extension I still hate that it takes up a whole spot in the toolbar, the address bar was a better place for site-specific extensions...
