### ISSUE TITLE
How to use?????????????

### ISSUE THREAD

**Issue by CrayzCrinkle** [natalieperna/layout-trello#30]
Please add some instructions to the internet on how to use this as there is nothing out ther./

**Comment by natalieperna** [comment]
Hi @CrayzCrinkle, check out the gif showing usage of the extension here: https://github.com/natalieperna/layout-trello#usage

Clicking the browser bar icon to rotate through the 3 different layout options is the only interface and use of this extension.

Closing this issue as solved, if you have any further questions just reply here and I'll reopen it.
