### ISSUE TITLE
Trello Layout - Feature Request

### ISSUE THREAD

**Issue by evanpcarter** [natalieperna/layout-trello#31]
Please pardon my ignorance...not sure how difficult (or even possible) this feature request would be? Is it possible to adjust this plugin to also allow for the lists to be scalable? In other words, some of my lists may only currently have 2 cards but others may be 15+. Rather than having to hover and scroll, it would be great to be able to adjust the lists to pull down/up to adjust to the size we select. 

Any thoughts? Thanks for the consideration!

**Comment by natalieperna** [comment]
This may be possible, but I think adjustable list sizes would add too much additional complexity to the plugin. (The simpler we keep it, the more likely I'll keep having time to maintain it whenever Trello makes updates that break it.)

The feature discussed in Issue #23 would probably satisfy your need well enough, but I won't likely have time to implement it anytime soon.
