### ISSUE TITLE
SO EFFICIENT!

### ISSUE THREAD

**Issue by CIOID** [natalieperna/layout-trello#32]
Thanks a lot Natalie Perna. What an excellent add on to Trello. Amazing and SO EFFICIENT! 

Roberto from Portugal

**Comment by natalieperna** [comment]
Glad you've found it useful. Reviews on the [Chrome Web Store](https://chrome.google.com/webstore/detail/list-layouts-for-trello/aldklnbenbdgfgfbflalmlddkkndgnlc/reviews) are always appreciated!

**Comment by CIOID** [comment]
VERY, VERY, USEFUL ´cause Scrolling Vertically is much more efficient and easy than scrolling horizontally

 

when we have BOARDS with many lists.

 

More…  when You have the Board totally in one Vertical “column” and you open a CARD the background is “empty”, clean… no distractions!

 

Thanks a LOT, NATALIE ! I´m a Trello fan and I´m very pleased with your TERRIFIC ADD ON!

 

Roberto

 

P.S. : I share with You this plugin for Trello (In case you have not yet ) and consider it useful. 

 

http://beingmrkenny.co.uk/web-extensions/list-highlighter-trello

 

 


http://premiumcoaching.pt/assemail/ass2017/images/arnaldoroberto.jpg


http://premiumcoaching.pt/assemail/ass2017/images/apc_02.jpg


http://premiumcoaching.pt/assemail/ass2017/images/apc_03.jpg


ARNALDO ROBERTO
FINANCE & ADM. MANAGER
PREMIUM COACHING
 <mailto:arnaldo.roberto@premiumcoaching.pt> arnaldo.roberto@premiumcoaching.pt
 <http://premiumcoaching.pt/> www.premiumcoaching.pt
TLM +351 968 160 640
TEL +351 211 582 204 


http://premiumcoaching.pt/assemail/ass2017/images/apc_03.jpg


LISBOA SEDE: Alameda da Beloura
Edifício 6, Office 4, Quinta da Beloura
2710-693 Sintra, Portugal
LISBOA FILIAL: Av. da República, n°6, 7°Esq
1050-191 Lisboa, Portugal 

 

 

De: Natalie Perna [mailto:notifications@github.com] 
Enviada: domingo, 14 de maio de 2017 22:59
Para: natalieperna/layout-trello
Cc: Roberto; Author
Assunto: Re: [natalieperna/layout-trello] SO EFFICIENT! (#32)

 

Glad you've found it useful. Reviews on the Chrome Web Store <https://chrome.google.com/webstore/detail/list-layouts-for-trello/aldklnbenbdgfgfbflalmlddkkndgnlc/reviews>  are always appreciated!
