### ISSUE TITLE
Works great! Would be even better to have both vertical AND horizontal at the same time to make vertical groups of lists stacked horizontally...is that possible?

### ISSUE THREAD

**Issue by robertbolduc** [natalieperna/layout-trello#6]

**Comment by elizabethswkim** [comment]
Yes, I second this feature request! (This comment is a dup of one I wrote under [closed issue #48](https://github.com/sudonatalie/layout-trello/issues/48).)

I'd love vertically and horizontally arrange lists (not just wrapping when they overflow past the right edge, but vertically stacking by choice, in addition to horizontal layout). In my today column, I want to split into multiple lists (ie, ongoing and emergent in the same column but in separate lists).
